import torch
import numpy as np
import os
import io
import zipfile
import logging
from typing import List, Dict

from app.ml.model_loader import load_model
from app.ml.model_config import ECGClassifier
from app.config import settings
from app.storage.minio_client import upload_bytes, get_presigned_url
from app.utils.helpers import s3_path

logger = logging.getLogger(__name__)


def _int8_hex_line(values: np.ndarray) -> str:
    """Convert array of float values to INT8 hex string."""
    clipped = np.clip(np.round(values * 127), -128, 127).astype(np.int8)
    hex_bytes = clipped.tobytes()
    # Format as Intel HEX style: groups of 16 bytes
    lines = []
    for i in range(0, len(hex_bytes), 16):
        chunk = hex_bytes[i : i + 16]
        lines.append(" ".join(f"{b:02X}" for b in chunk))
    return "\n".join(lines)


def generate_hex_content(layer_name: str, weight_tensor: torch.Tensor) -> str:
    """Generate .hex file content for a given weight tensor."""
    weights = weight_tensor.detach().cpu().float().numpy().flatten()
    header = f"// {layer_name} | shape: {list(weight_tensor.shape)} | {len(weights)} values\n"
    header += f"@00000000\n"
    body = _int8_hex_line(weights)
    return header + body + "\n"


def extract_layer_weights(model: ECGClassifier) -> List[Dict]:
    """Extract all layer weights from the model."""
    layers = []
    addr = 0

    for name, param in model.named_parameters():
        if param.requires_grad:
            weights = param.detach().cpu().float().numpy().flatten()
            num_weights = len(weights)
            layers.append(
                {
                    "layer": name,
                    "filename": f"{name.replace('.', '_')}.hex",
                    "tensor": param,
                    "weight_count": num_weights,
                    "size_kb": round(num_weights / 1024, 3),
                    "memory_address_start": f"0x{addr:08X}",
                    "memory_address_end": f"0x{addr + num_weights:08X}",
                }
            )
            addr += num_weights

    return layers


def generate_hex_files(session_id: str) -> dict:
    """
    Generate HEX files for all model layers, package as ZIP, upload to MinIO.
    Returns file manifest and download URL.
    """
    model_path = settings.QUANTIZED_MODEL_PATH
    if not os.path.exists(model_path):
        model_path = settings.MODEL_PATH

    model = load_model(model_path)
    model.eval()

    layers = extract_layer_weights(model)

    # Build ZIP in memory
    zip_buffer = io.BytesIO()
    file_manifest = []
    total_memory = 0

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        readme_lines = ["# FPGA Weight Files\n", "Generated by CardioFPGA backend\n\n", "## Memory Map\n"]

        for layer_info in layers:
            hex_content = generate_hex_content(layer_info["layer"], layer_info["tensor"])
            zf.writestr(layer_info["filename"], hex_content)

            file_manifest.append(
                {
                    "layer": layer_info["layer"],
                    "filename": layer_info["filename"],
                    "size_kb": layer_info["size_kb"],
                    "weight_count": layer_info["weight_count"],
                    "memory_address_start": layer_info["memory_address_start"],
                    "memory_address_end": layer_info["memory_address_end"],
                }
            )
            total_memory += layer_info["weight_count"]
            readme_lines.append(
                f"- {layer_info['filename']}: {layer_info['weight_count']} weights "
                f"@ {layer_info['memory_address_start']}\n"
            )

        zf.writestr("README.md", "".join(readme_lines))

    zip_bytes = zip_buffer.getvalue()
    zip_obj = s3_path(session_id, "hex_files", "fpga_weights.zip")
    upload_bytes(zip_obj, zip_bytes, "application/zip")
    download_url = get_presigned_url(zip_obj)

    bram_blocks = max(1, int(np.ceil(total_memory / 1024)))

    return {
        "files": file_manifest,
        "archive": {
            "filename": "fpga_weights.zip",
            "size_mb": round(len(zip_bytes) / (1024 * 1024), 3),
            "download_url": download_url,
            "object_name": zip_obj,
        },
        "memory_map": {
            "total_weights": total_memory,
            "total_memory_kb": round(total_memory / 1024, 1),
            "recommended_bram_blocks": bram_blocks,
        },
    }
